version: "3.8"

services:
  kafka:
    image: apache/kafka:3.8.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      # Kafka lắng nghe tất cả các interface
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      # Địa chỉ quảng bá cho producer/consumer
      # Nếu chạy producer/consumer local host, dùng localhost:9092
      # Nếu chạy trong Docker container, dùng kafka:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    volumes:
      - kafka_data:/var/lib/kafka/data

  producer:
    build:
      context: ./kafka
    depends_on:
      - kafka
    # Trong container, bootstrap_servers phải là kafka:9092
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    command: ["python", "producer.py"]

  spark_consumer:
    build:
      context: ./spark
    depends_on:
      - kafka
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    volumes:
      - spark_data:/app/data
      - spark_checkpoint:/app/data/checkpoint
    command: ["python", "spark_stream.py"]

volumes:
  kafka_data:
  spark_data:
  spark_checkpoint:
