FROM apache/spark-py:latest

USER root

WORKDIR /app

COPY main.py .

COPY ./jars/hadoop-aws-3.3.4.jar /opt/spark/jars/
COPY ./jars/aws-java-sdk-bundle-1.12.262.jar /opt/spark/jars/
COPY ./jars/spark-sql-kafka-0-10_2.12-3.5.1.jar /opt/spark/jars/

RUN chown -R 185:185 /app /opt/spark/jars

USER 185