# ===========================
# HDFS NAMENODE
# ===========================
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hdfs-namenode
  namespace: hugedata
spec:
  serviceName: hdfs-namenode
  replicas: 1
  selector:
    matchLabels:
      app: hdfs-namenode
  template:
    metadata:
      labels:
        app: hdfs-namenode
    spec:
      containers:
      - name: namenode
        image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
        resources:
          limits:
            memory: "600Mi" # Namenode cần nhớ metadata nên cần cao hơn Datanode một chút
          requests:
            memory: "400Mi"
        env:
        - name: CLUSTER_NAME
          value: hadoop-cluster
        - name: CORE_CONF_fs_defaultFS
          value: hdfs://hdfs-namenode:8020
        - name: HDFS_CONF_dfs_permissions
          value: "false"
        - name: HDFS_CONF_dfs_namenode_datanode_registration_ip_hostname_check
          value: "false"
        ports:
        - containerPort: 9870
        - containerPort: 8020
        volumeMounts:
        - name: hdfs-name
          mountPath: /hadoop/dfs/name
  volumeClaimTemplates:
  - metadata:
      name: hdfs-name
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 5Gi

---
apiVersion: v1
kind: Service
metadata:
  name: hdfs-namenode
  namespace: hugedata
spec:
  ports:
  - port: 8020
    name: rpc
  - port: 9870
    name: web
  selector:
    app: hdfs-namenode

# ===========================
# HDFS DATANODE HEADLESS SERVICE
# ===========================
---
apiVersion: v1
kind: Service
metadata:
  name: hdfs-datanode-headless
  namespace: hugedata
spec:
  clusterIP: None
  selector:
    app: hdfs-datanode
  ports:
  - port: 9864
    name: data

# ===========================
# HDFS DATANODE STATEFULSET
# ===========================
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hdfs-datanode
  namespace: hugedata
spec:
  serviceName: hdfs-datanode-headless
  replicas: 1
  selector:
    matchLabels:
      app: hdfs-datanode
  template:
    metadata:
      labels:
        app: hdfs-datanode
    spec:
      containers:
      - name: datanode
        image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
        resources:
          limits:
            memory: "600Mi"
          requests:
            memory: "400Mi"
        env:
        - name: CORE_CONF_fs_defaultFS
          value: hdfs://hdfs-namenode:8020
        - name: SERVICE_PRECONDITION
          value: "hdfs-namenode:8020"
        - name: HDFS_CONF_dfs_namenode_datanode_registration_ip_hostname_check
          value: "false"
        ports:
        - containerPort: 9864
        volumeMounts:
        - name: hdfs-data
          mountPath: /hadoop/dfs/data
  volumeClaimTemplates:
  - metadata:
      name: hdfs-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 5Gi
