apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: spark-hdfs-reader
  namespace: hugedata

spec:
  type: Python
  pythonVersion: "3"
  mode: cluster

  image: spark-application:dev
  imagePullPolicy: IfNotPresent

  mainApplicationFile: local:///app/hdfs_reader.py
  sparkVersion: 3.5.1

  sparkConf:
    spark.hadoop.fs.defaultFS: "hdfs://hdfs-namenode:8020"

    spark.cassandra.connection.host: "cassandra.hugedata.svc.cluster.local"
    spark.cassandra.connection.port: "9042"

    spark.jars: "local:///opt/spark/jars/spark-cassandra-connector-assembly_2.12-3.5.1.jar"

  driver:
    cores: 1
    memory: 512m
    serviceAccount: default
    env:
      - name: CASSANDRA_HOST
        value: "cassandra.hugedata.svc.cluster.local"
      - name: HDFS_NAMENODE
        value: "hdfs://hdfs-namenode:8020"
    securityContext:
      runAsUser: 185
      runAsGroup: 185
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      seccompProfile:
        type: RuntimeDefault

  executor:
    instances: 1
    cores: 1
    memory: 768m
    env:
      - name: CASSANDRA_HOST
        value: "cassandra.hugedata.svc.cluster.local"
      - name: HDFS_NAMENODE
        value: "hdfs://hdfs-namenode:8020"
    securityContext:
      runAsUser: 185
      runAsGroup: 185
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      seccompProfile:
        type: RuntimeDefault
