apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: spark-hdfs-reader
  namespace: hugedata
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: spark-application:dev
  imagePullPolicy: IfNotPresent
  mainApplicationFile: local:///app/hdfs_reader.py
  sparkVersion: 3.5.1

  sparkConf:
    spark.hadoop.fs.defaultFS: hdfs://hdfs-namenode:8020

  driver:
    cores: 1
    memory: 512m
    serviceAccount: default

  executor:
    instances: 1
    cores: 1
    memory: 512m
