# ---------- BASE ----------
FROM python:3.10-slim AS base
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    DEBIAN_FRONTEND=noninteractive

# Install system libs in one layer, clean cache properly
RUN apt-get update -qq && \
    apt-get install -y --no-install-recommends \
        libgl1 \
        libglib2.0-0 && \
    rm -rf /var/lib/apt/lists/*

# ---------- BUILDER ----------
FROM base AS builder

# Use a requirements file to allow caching
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# ---------- FINAL ----------
FROM base AS final
WORKDIR /app
COPY --from=builder /usr/local/lib/python3.10 /usr/local/lib/python3.10
COPY . .

CMD ["python", "producer.py"]
