FROM python:3.10-slim

RUN apt-get update && apt-get install -y \
    libgl1 \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir \
    numpy \
    kafka-python \
    requests \
    opencv-python-headless

WORKDIR /app
COPY . .

CMD ["python", "producer.py"]
